baseURL = "https://datavis.berlin"
languageCode = "en-gb"
title = "Datavis Meetup Berlin"
disableKinds = ["taxonomy", "taxonomyTerm", "jobs", "section", "tags"]
invisibleSections = ["jobs"]

[params]
  description = "An open list to the data visualisation scene in Berlin. All people, things and places that are visualisation, infographic, data art, data journalism, research, and data tool related, are welcome!"
  author = "zeto"
  telegram = "visber"
  source = "https://github.com/Data-Visualization-Berlin/Datavis-Berlin-Website"
  imprint = "https://jonasparnow.com/imprint"
  privacy = "https://jonasparnow.com/privacy"