title = "Data visualisation Berlin"
invisibleSections = ["jobs"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "An open list to the data visualisation scene in Berlin. All people, things and places that are related to visualisation, infographic, data art, data journalism, reasearch, and data tools are welcome!"
  keywords = "data visualisation visualization design infographic infromation graphic data-driven journalism ddj interfacedesgin"
  author = "Jonas Parnow"
  twitter = "zeto"
  telegram = "visber"
  source = "https://github.com/Data-Visualization-Berlin/Datavis-Berlin-Website"
  imprint = "https://jonasparnow.com/imprint"
  privacy = "https://jonasparnow.com/privacy"

  [params.switch]
  	en = "Switch to English"
  	de = "Zu Deutsch wechseln"

[languages]
  [languages.en]
    baseURL = "https://datavis.berlin"
    LanguageName = "English"
    languageCode = "en"
    weight = 1
    disableKinds = ["taxonomy", "taxonomyTerm", "jobs", "section", "tags"]
  [languages.de]
    title = "Daten Visualisierung Berlin"
    baseURL = "https://de.datavis.berlin"
    description = "Eine offene List der Datenvisualisierungsszene in Berlin. Alle Menschen, Dinge und Orte, die mit Visualisierung, Infografik, Datenkunst, Datenjournalismus, Forschung und Datenanwendungen verwandt sind, sind willkommen!"
    keywords = "Visualisierung Daten Infografik Design Informationsgrafik Datenjournalismus DDJ Statistik Interfacedesign"
    LanguageName = "Deutsch"
    languageCode = "de"
    weight = 2
    disableKinds = ["taxonomy", "taxonomyTerm", "jobs", "section", "tags"]
  [languages.it]
    baseURL = "https://it.datavis.berlin"
    title = "Data visualization Berlin"
    description = "Una lista aperta dedicata alla scena berlinese della data visualisation. Tutto ciò che riguarda persone, cose e luoghi che riguardano la visualizzazione dati, infografica, giornalismo con i dati, ricerca e data tools è benvenuto!"
    keywords = "data visualization visualizzatione dati design infografiche information design grafica con i dati giornalismo con i dati interfacedesign data-driven journalism"
    LanguageName = "Italiano"
    languageCode = "it"
    weight = 2
    disableKinds = ["taxonomy", "taxonomyTerm", "jobs", "section", "tags"]
  [languages.es]
    baseURL = "https://es.datavis.berlin"
    title = "Data visualization Berlin"
    description = "Una lista abierta de la escena de visualización de datos en Berlín. Toda las personas, cosas y lugares relacionados con la visualización, la infográfica, el data art, el periodismo de datos, la investigación y herramientas útiles son bienvenidos!"
    keywords = "diseño de visualización de datos infografía información gráfica periodismo de datos ddj interfacedesign"
    LanguageName = "Español"
    languageCode = "es"
    weight = 2
    disableKinds = ["taxonomy", "taxonomyTerm", "jobs", "section", "tags"]
